cache: 5m
commands:
- lang: qr
  run: 'qrencode -o "{{output}}" -t png'
- lang: mermaid
  run: 'bunx mmdc -s 4 -i - -o "{{output}}" --quiet'
- lang: '*'
  run: 'silicon -l "{{lang}}" -o "{{output}}"'
